workflows:
  android_apk:
    name: Android APK (split per ABI)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      android: latest
      java: 17
      vars:
        # Usado para gerar local.properties caso falte
        ANDROID_SDK_DIR: $ANDROID_SDK_ROOT
        FLUTTER_SDK_DIR: $FCI_FLUTTER_PATH

    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      # 1) Checagem rápida de versões/arquivos (debug de ambiente)
      - name: Print ambiente
        script: |
          echo "Flutter: $(flutter --version)"
          echo "Java: $(java -version 2>&1 | head -n1)"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
          echo "FCI_FLUTTER_PATH=$FCI_FLUTTER_PATH"
          echo "PWD=$(pwd)"

      # 2) Instala SDK Platform 36 e Build-tools 34 (pedidos pelos plugins)
      - name: Instalar Android SDKs necessários
        script: |
          yes | sdkmanager --licenses || true
          yes | sdkmanager "platforms;android-36" "build-tools;34.0.0"

      # 3) Garante android/local.properties
      - name: Garantir local.properties
        script: |
          mkdir -p android
          echo "sdk.dir=${ANDROID_SDK_DIR}" > android/local.properties
          echo "flutter.sdk=${FLUTTER_SDK_DIR}" >> android/local.properties
          echo "=== android/local.properties ==="
          cat android/local.properties

      # 4) Garantir AGP 8.6.0 e Kotlin 2.1.0 no settings.gradle
      - name: Ajustar settings.gradle (AGP/Kotlin)
        script: |
          echo "=== Antes (settings.gradle) ==="
          sed -n '1,200p' android/settings.gradle || true

          # Seta Kotlin Gradle plugin 2.1.0
          perl -0777 -pe 's/id "org\.jetbrains\.kotlin\.android"\s+version\s+"[^"]+"/id "org.jetbrains.kotlin.android" version "2.1.0"/' -i android/settings.gradle

          # Seta Android Gradle Plugin 8.6.0
          perl -0777 -pe 's/id "com\.android\.application"\s+version\s+"[^"]+"/id "com.android.application" version "8.6.0"/' -i android/settings.gradle

          echo "=== Depois (settings.gradle) ==="
          sed -n '1,200p' android/settings.gradle || true

      # 5) Forçar compileSdk = 36 e remover stdlib direta
      - name: Ajustar app/build.gradle (compileSdk 36 e remover stdlib)
        script: |
          echo "=== Antes (app/build.gradle) ==="
          sed -n '1,200p' android/app/build.gradle || true

          # compileSdk 36
          perl -0777 -pe 's/compileSdk\s*\d+/compileSdk 36/g' -i android/app/build.gradle

          # Remover linha explícita de kotlin-stdlib (se existir)
          sed -i.bak '/kotlin-stdlib/d' android/app/build.gradle || true
          rm -f android/app/build.gradle.bak

          echo "=== Depois (app/build.gradle) ==="
          sed -n '1,200p' android/app/build.gradle || true
          echo "compileSdk encontrado:"
          grep -n "compileSdk" android/app/build.gradle || true

      # 6) Pub get
      - name: Flutter pub get
        script: flutter pub get

      # 7) Build APK por ABI (release)
      - name: Build APK (split per ABI)
        script: |
          flutter build apk --release --split-per-abi
          ls -R build/app/outputs || true

    artifacts:
      - build/app/outputs/apk/release/*.apk
      - build/app/outputs/flutter-apk/*-release.apk
