workflows:
  android_apk:
    name: Android APK (Debug)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      # Versão do Flutter a usar (ajuste se quiser '3.24.x' etc.)
      flutter: stable
      # Variáveis úteis
      vars:
        ANDROID_HOME: /usr/local/share/android-sdk

    scripts:
      # (Opcional) Log de arquivos-chave pra garantir que o CI está lendo suas mudanças
      - name: Show important project files
        script: |
          echo "=== android/settings.gradle ==="
          cat android/settings.gradle
          echo "=== android/app/build.gradle ==="
          cat android/app/build.gradle
          echo "=== android/local.properties ==="
          cat android/local.properties || true

      # Aceita licenças do SDK
      - name: Accept Android SDK licenses
        script: |
          yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager --licenses

      # Instala Platform 36, Build-Tools 34 e NDK 26.1 (plugins pediam isso)
      - name: Install Android SDK/NDK
        script: |
          yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager \
            "platforms;android-36" \
            "build-tools;34.0.0" \
            "platform-tools" \
            "ndk;26.1.10909125"

      # Limpa caches de Kotlin/Gradle pra evitar conflito entre versões (2.2.0 vs 2.0.x)
      - name: Clean Gradle/Kotlin caches
        script: |
          rm -rf ~/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin || true
          rm -rf ~/.gradle/caches/transforms-* ~/.gradle/caches/jars-* || true
          flutter clean

      # Resolve dependências
      - name: Flutter pub get
        script: flutter pub get

      # Compila APK (debug) separado por ABI
      - name: Build APK (debug split per ABI)
        script: flutter build apk --debug --split-per-abi

    artifacts:
      - build/app/outputs/flutter-apk/*.apk

    publishing:
      # (Opcional) Envia por e-mail o artefato
      email:
        recipients:
          - seu-email@exemplo.com
        notify:
          success: true
          failure: true
